version: '3.8'

services:
  api:
    depends_on:
      - db
    build: .
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: 'mysql'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - .dbdata:/var/lib/mysql

volumes:
  db: